# Generated by Django 5.2 on 2025-05-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cooloff', 'In Cooloff')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('urls_total', models.IntegerField(default=0)),
                ('urls_processed', models.IntegerField(default=0)),
                ('rate_limit_hits', models.IntegerField(default=0)),
                ('current_rate', models.FloatField(default=1.0)),
                ('cooloff_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_proxies_count', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0)),
                ('last_request_time', models.DateTimeField(blank=True, null=True)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='crawler.crawljob')),
                ('current_proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.proxy')),
            ],
        ),
        migrations.CreateModel(
            name='CrawledURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('content', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content_type', models.CharField(choices=[('html', 'HTML'), ('markdown', 'Markdown')], default='html', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='crawler.crawljob')),
                ('proxy_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawled_urls', to='crawler.proxy')),
            ],
        ),
    ]
