# Generated by Django 5.2 on 2025-05-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cooloff', 'In Cooloff'), ('killed', 'Killed')], default='pending', max_length=20),
        ),
    ]
