# Generated by Django 5.2 on 2025-05-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_crawljob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledurl',
            name='retry_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('timeout', 'Timeout'), ('retry_pending', 'Retry Pending'), ('failed', 'Failed')], default='pending', max_length=15),
        ),
    ]
