# Generated by Django 5.2 on 2025-05-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_crawledurl_retry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledurl',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='crawljob',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
    ]
