# Generated by Django 5.2 on 2025-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_crawledurl_screenshot_path_crawljob_debug_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='parallel_workers',
            field=models.IntegerField(default=1),
        ),
    ]
