# Generated by Django 5.2 on 2025-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_crawljob_parallel_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawledurl',
            name='structured_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
