# Generated by Django 5.2 on 2025-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_crawledurl_structured_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='proxy_countries',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
