# Generated by Django 5.2 on 2025-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0007_crawljob_proxy_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='reshuffle_proxies',
            field=models.BooleanField(default=False),
        ),
    ]
